# -*- coding: utf-8 -*-
"""2548512_DL_LAB2_Anurag_Chowdhury.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fy9eTWBfWcYtPCQ1zIRxK3yIKZzteafd

# Deep Feedforward Neural Network for Fashion MNIST Classification
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

train_data = datasets.FashionMNIST(root='./data', train=True, transform=transform, download=True)
test_data = datasets.FashionMNIST(root='./data', train=False, transform=transform, download=True)

train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)

#At least three hidden layers with ReLU
# Input size = 28*28 = 784
layer1 = nn.Linear(784, 512)
layer2 = nn.Linear(512, 256)
layer3 = nn.Linear(256, 128)
layer4 = nn.Linear(128, 10)

#Combine all parameters for optimizer
params = list(layer1.parameters()) + list(layer2.parameters()) \
       + list(layer3.parameters()) + list(layer4.parameters())

#Loss Function & Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(params, lr=0.001)

#Forward Function
def forward(x):
    x = x.view(-1, 28*28)          # Flatten
    x = F.relu(layer1(x))
    x = F.relu(layer2(x))
    x = F.relu(layer3(x))
    x = layer4(x)
    return x

#Training
epochs = 10
train_losses = []
train_accuracies = []

for epoch in range(epochs):
    running_loss = 0
    correct = 0
    total = 0

    for images, labels in train_loader:
        outputs = forward(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    acc = 100 * correct / total
    train_losses.append(running_loss / len(train_loader))
    train_accuracies.append(acc)

    print(f"Epoch {epoch+1}/{epochs}, Loss: {running_loss/len(train_loader):.4f}, Accuracy: {acc:.2f}%")

#Test
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        outputs = forward(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_acc = 100 * correct / total
print(f"Test Accuracy: {test_acc:.2f}%")

"""# ADVANCED TASK 1 – Network Depth & Width Experiments"""

#Shallow Network (1 Hidden Layer)
A1 = nn.Linear(784, 256)
A2 = nn.Linear(256, 10)

paramsA = list(A1.parameters()) + list(A2.parameters())

def forwardA(x):
    x = x.view(-1, 784)
    x = F.relu(A1(x))
    x = A2(x)
    return x

#Medium Network (3 Hidden Layers)
B1 = nn.Linear(784, 512)
B2 = nn.Linear(512, 256)
B3 = nn.Linear(256, 128)
B4 = nn.Linear(128, 10)

paramsB = list(B1.parameters()) + list(B2.parameters()) + \
          list(B3.parameters()) + list(B4.parameters())

def forwardB(x):
    x = x.view(-1, 784)
    x = F.relu(B1(x))
    x = F.relu(B2(x))
    x = F.relu(B3(x))
    x = B4(x)
    return x

#Deep Network (5 Hidden Layers)
C1 = nn.Linear(784, 512)
C2 = nn.Linear(512, 512)
C3 = nn.Linear(512, 256)
C4 = nn.Linear(256, 128)
C5 = nn.Linear(128, 64)
C6 = nn.Linear(64, 10)

paramsC = list(C1.parameters()) + list(C2.parameters()) + \
          list(C3.parameters()) + list(C4.parameters()) + \
          list(C5.parameters()) + list(C6.parameters())

def forwardC(x):
    x = x.view(-1, 784)
    x = F.relu(C1(x))
    x = F.relu(C2(x))
    x = F.relu(C3(x))
    x = F.relu(C4(x))
    x = F.relu(C5(x))
    x = C6(x)
    return x

#Training
def train_model(forward_fn, params, epochs=5):
    optimizer = optim.Adam(params, lr=0.001)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        running_loss, correct, total = 0, 0, 0

        for images, labels in train_loader:
            outputs = forward_fn(images)
            loss = criterion(outputs, labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        print(f"Epoch {epoch+1}, Loss = {running_loss/len(train_loader):.4f}, "
              f"Train Acc = {100*correct/total:.2f}%")



#Test
def evaluate_model(forward_fn):
    correct, total = 0, 0
    with torch.no_grad():
        for images, labels in test_loader:
            outputs = forward_fn(images)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    return 100 * correct / total

#1-Layer
print("\nTraining Model A (1 Hidden Layer)")
train_model(forwardA, paramsA)
print("Test Accuracy:", evaluate_model(forwardA))

#3-Layer
print("\nTraining Model B (3 Hidden Layers)")
train_model(forwardB, paramsB)
print("Test Accuracy:", evaluate_model(forwardB))

#5-Layer
print("\nTraining Model C (5 Hidden Layers)")
train_model(forwardC, paramsC)
print("Test Accuracy:", evaluate_model(forwardC))

"""#ADVANCED TASK 2 – Activation Function Study"""

def relu(x):
    return F.relu(x)

def sigmoid(x):
    return torch.sigmoid(x)

def tanh(x):
    return torch.tanh(x)

def leaky(x):
    return F.leaky_relu(x, negative_slope=0.01)

def forward_act(x, activation):
    x = x.view(-1, 784)
    x = activation(B1(x))
    x = activation(B2(x))
    x = activation(B3(x))
    x = B4(x)
    return x

#Training
def train_with_activation(activation_fn, params, epochs=5):
    optimizer = optim.Adam(params, lr=0.001)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        running_loss = 0
        correct = 0
        total = 0

        for images, labels in train_loader:
            outputs = forward_act(images, activation_fn)
            loss = criterion(outputs, labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        print(f"Epoch {epoch+1}, Loss={running_loss/len(train_loader):.4f}, "
              f"Accuracy={100*correct/total:.2f}%")

#Testing
def test_with_activation(activation_fn):
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            outputs = forward_act(images, activation_fn)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    return 100 * correct / total

#ReLU
print("\nUsing ReLU Activation")
train_with_activation(relu, paramsB)
print("Test Accuracy:", test_with_activation(relu))

#Sigmoid
print("\nUsing Sigmoid Activation")
train_with_activation(sigmoid, paramsB)
print("Test Accuracy:", test_with_activation(sigmoid))

#Tanh
print("\nUsing Tanh Activation")
train_with_activation(tanh, paramsB)
print("Test Accuracy:", test_with_activation(tanh))

#Leaky ReLU
print("\nUsing Leaky ReLU Activation")
train_with_activation(leaky, paramsB)
print("Test Accuracy:", test_with_activation(leaky))

"""#ADVANCED TASK 3 – Visualize Hidden Layer Activations"""

def visualize_activations(image):
    x = image.view(-1, 784)

    h1 = F.relu(B1(x))
    h2 = F.relu(B2(h1))
    h3 = F.relu(B3(h2))

    plt.figure(figsize=(12,3))
    plt.subplot(1,3,1)
    plt.imshow(h1.view(32,16).detach(), cmap='viridis')
    plt.title("Layer 1 Features")

    plt.subplot(1,3,2)
    plt.imshow(h2.view(16,16).detach(), cmap='viridis')
    plt.title("Layer 2 Features")

    plt.subplot(1,3,3)
    plt.imshow(h3.view(16,8).detach(), cmap='viridis')
    plt.title("Layer 3 Features")

    plt.show()

sample_img, _ = next(iter(train_loader))
visualize_activations(sample_img[1])

import matplotlib.pyplot as plt

plt.imshow(sample_img[1].squeeze(), cmap='gray')
plt.title("Sample Fashion MNIST Image")
plt.axis('off')
plt.show()

"""#Interpretation
- Layer 1: Edge detectors, curves, basic textures

- Layer 2: Shapes like sleeves, soles, straps

- Layer 3: High-level patterns for classification (dress vs. shoe vs. shirt)

As depth increases, features become more abstract and class-specific.
"""